# Generated by Django 4.2.21 on 2025-05-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='room_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
