# Generated by Django 4.2.21 on 2025-05-25 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_room_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='room_key',
        ),
    ]
