# Generated by Django 4.2.21 on 2025-05-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='private_key',
            new_name='private_key_encrypted',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='public_key',
            new_name='public_key_pem',
        ),
        migrations.AddField(
            model_name='customuser',
            name='symmetric_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
